//
// Created by teamt on 04/10/2019.
//
"""
#include "TemplateGenerator.h"
#include "../types/arinc_module.h"
#include "../types/channel.h"
#include "../types/error_id_action.h"
#include "../types/error_id_level.h"
#include "../types/error_id_type.h"
#include "../types/memory_requiremenets.h"
#include "../types/module_hm_table.h"
#include "../types/partition.h"
#include "../types/partition_hm_table.h"
#include "../types/partition_memory.h"
#include "../types/port_mapping.h"
#include "../types/port_type.h"
#include "../types/process.h"
#include "../types/queuing_port.h"
#include "../types/sampling_port.h"
#include "../types/schedule.h"
#include "../types/system_hm_table.h"
#include "../types/system_state_entry.h"

"""
//{/*PortType*/
//"nameType",
//10,
//{/*PortMappingType*/
//	{/*PseudoPartition*/
//		"nameType",
//		"physicalAdress",
//		"nameType(procedure)"
//	},
//	{/*StandardPartition*/
//		10,
//		"nameType",
//		"nameType",
//		20
//	}
//}
//}
//
//{/*Process*/
//"nameType",
//"stacksSize",
//{/*Criticality*/ },
//false,
//"entrypoint"
//}


//number generated by code generator
Partition partitions[10]{
	{ /*partition*/
		//identifier valuetype??
		"nametype",
		0,
		false,
		"entry point",
		{/*SamplingPort array??*/
			{/*PortType*/
				"nameType",
				10,
				{/*PortMappingType*/
					{/*PseudoPartition*/
						"nameType",
						"physicalAdress",
						"nameType(procedure)"
					},
					{/*StandardPartition*/
						10,
						"nameType",
						"nameType",
						20
					}
				}
			},
			0.0f
		},
		{/*QueuingPort array??*/
			{/*PortType*/
				"nameType",
				10,
				{/*PortMappingType*/
					{/*PseudoPartition*/
						"nameType",
						"physicalAdress",
						"nameType(procedure)"
					},
					{/*StandardPartition*/
						10,
						"nameType",
						"nameType",
						20
					},
				}
			},
			0
		},
		{/*Process array??*/
			"nameType",
			"stacksSize",
			{/*Criticality*/},
			false,
			"entrypoint"
		}
	}
};