//
// Created by teamt on 04/10/2019.
//
"""
#include "TemplateGenerator.h"
#include "../types/arinc_module.h"
#include "../types/channel.h"
#include "../types/error_id_action.h"
#include "../types/error_id_level.h"
#include "../types/error_id_type.h"
#include "../types/memory_requiremenets.h"
#include "../types/module_hm_table.h"
#include "../types/partition.h"
#include "../types/partition_hm_table.h"
#include "../types/partition_memory.h"
#include "../types/port_mapping.h"
#include "../types/port_type.h"
#include "../types/process.h"
#include "../types/queuing_port.h"
#include "../types/sampling_port.h"
#include "../types/schedule.h"
#include "../types/system_hm_table.h"
#include "../types/system_state_entry.h"

"""


//number generated by code generator
Partition partitions[10]{
	{
	indentfierValueType partitionIdentifier;            /* required */
		std::optional<nameType> partitionName;              /* optional */
		CriticalityType criticality = LEVEL_A;
		bool systemPartition = false;
		char[MAXLENGTH] entryPoint;                         /* required */
		SamplingPort samplingPort[MAX_NUMBER_SAMPLING_PORT];
		QueuingPort queuingPort[MAX_NUMBER_QUEUING_PORT];
		Process process[MAX_NUMBER_PROCESS];
}
};
