//
// Created by teamt on 04/10/2019.
//
"""
#include "TemplateGenerator.h"
#include "../types/arinc_module.h"
#include "../types/channel.h"
#include "../types/error_id_action.h"
#include "../types/error_id_level.h"
#include "../types/error_id_type.h"
#include "../types/memory_requiremenets.h"
#include "../types/module_hm_table.h"
#include "../types/partition.h"
#include "../types/partition_hm_table.h"
#include "../types/partition_memory.h"
#include "../types/port_mapping.h"
#include "../types/port_type.h"
#include "../types/process.h"
#include "../types/queuing_port.h"
#include "../types/sampling_port.h"
#include "../types/schedule.h"
#include "../types/system_hm_table.h"
#include "../types/system_state_entry.h"

"""

//number generated by code generator
Partition partitions[10]{
	{ /*partition*/
		//identifier valuetype??
		"nametype",
		0,
		false,
		"entry point",
		{{/*SamplingPort array??*/
			{/*PortType*/
				"nameType",
				1,
				{/*PortMappingType*/
					{/*PseudoPartition*/
						"nameType",
						"physicalAdress",
						"nameType(procedure)"
					},
					{/*StandardPartition*/
						1,
						"nameType",
						"nameType",
						2
					}
				}
			},
			0.0f
		}},
		{{/*QueuingPort array??*/
			{/*PortType*/
				"nameType",
				1,
				{/*PortMappingType*/
					{/*PseudoPartition*/
						"nameType",
						"physicalAdress",
						"nameType(procedure)"
					},
					{/*StandardPartition*/
						1,
						"nameType",
						"nameType",
						2
					},
				}
			},
			0
		}},
		{{/*Process array??*/
			"nameType",
			"stacksSize",
			LEVEL_A,
			false,
			"entrypoint"
		}}
	}
};

ModuleSchedule moduleSchedule = {
	{/*PartitionSchedule*/
		0,
		"nameType",
		0.0f,
		0.0f,
		{{ /*WindowSchedule*/
				0,
				0.0f
				0.0f
				true
		}}
	}
}

