ROOT=		../../../../../

OBJS=	tacoskerneltest.o \
		apex_buffer_tests.o \
		apex_mutex_tests.o

all: $(TARGET)

.PHONY: clean all

clean: common-clean

#include $(ROOT)/misc/common-pi4.mk
include $(ROOT)/src/misc/common-rules.mk