ROOT=		../../

OBJS=		consumer_part.o \
			dummy_part.o \
			fib_part.o \ 

all: $(TARGET)

.PHONY: clean all

clean: common-clean

#include $(ROOT)/misc/common-pi4.mk
include $(ROOT)/src/misc/common-rules.mk