ROOT=		../../../../

OBJS= apex_blackboard.o \
		apex_buffer.o \
		apex_queuing_port.o \
		apex_time.o \
		apex_event.o \
		apex_mutex.o

all: $(TARGET)

.PHONY: clean all

clean: common-clean

include $(ROOT)/src/misc/common-rules.mk

