ROOT=		../../../../

OBJS=		partitionscheduling.o  \
			process_schedule.o \
			exceptionstub64.o


all: $(TARGET)

.PHONY: clean all

clean: common-clean

#include $(ROOT)/misc/common-pi4.mk

include $(ROOT)/src/misc/common-rules.mk
