#
# Makefile
#
export TACOS_PATH=$(CURDIR)/../../
export CIRCLE_PATH=$(TACOS_PATH)/aarch/rasp4

CIRCLEHOME = ../../aarch/rasp4

OBJS	= main.o kernel.o

LIBS	= $(CIRCLEHOME)/lib/libcircle.a

include $(CIRCLEHOME)/Rules.mk
